### ISSUE TITLE
Separate the list in vertical markets

### ISSUE THREAD

**Issue by hvelarde** [plone/paragon.addons#1]
I think it would be better to have lists for different kind of sites; for instance, a news media site could benefit from a Liveblog, while a company site maybe not.

I propose the following to start:
- Company
- Education
- Government
- Intranet
- Media

**Comment by polyester** [comment]
-1

description of the _functionality_ helps. Presuming what fits well on what kind of site, does not. 

To stick with your example: a company might totally want a liveblog, during their product launch with breathless fans around the globe. Or a nonprofit might use a liveblog during an action.

So labeling it in this way has two problems:
- who is going to do it, and  more importantly maintain it
- and users might totally miss useful add-ons, because they will not look into the 'right' vertical while they could make use of the add-on in other ways.

**Comment by tkimnguyen** [comment]
I have to say I agree with @polyester because when I tried to create a "PloneEdu buildout" I ran into that exact problem: even though I used all of the add-ons that I included in that buildout, there was in fact no particular reason why the exact same buildout wouldn't have applied to any other multi-departmental organization.

Looking at the current list, having categories like "search" and "forms" and "page layout" and "social" would be appropriate.
